[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
anala_lending = "7h6qLdbjD12HspcDc1vk8uCsf2STHGWJSkHH9FvyYNLG"

[programs.devnet]
anala_lending = "7h6qLdbjD12HspcDc1vk8uCsf2STHGWJSkHH9FvyYNLG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
